[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.0.0"

[[constraint]]
  name = "github.com/grpc-ecosystem/grpc-gateway"
  branch = "master"

[[constraint]]
  name = "golang.org/x/net"
  branch = "master"

[[constraint]]
  name = "google.golang.org/genproto"
  branch = "master"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.11.3"

[prune]
  go-tests = true
  unused-packages = true
